- name: Process Images
        run: |
          mkdir -p assets/data/eglise/img/noimh/old
          # On cherche les jpg, jpeg et png à la racine du dossier noimh
          find assets/data/eglise/img/noimh/ -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | while read img; do
            filename=$(basename "$img")
            basename="${filename%.*}"
            webp_path="assets/data/eglise/img/noimh/${basename}.webp"
            
            echo "Vérification de $filename..."

            # 1. Si le WebP n'existe pas encore, on le crée
            if [ ! -f "$webp_path" ]; then
              echo "-> Création du WebP pour $filename"
              cwebp -q 80 "$img" -o "$webp_path"
            else
              echo "-> Le WebP existe déjà pour $filename, on passe à l'archivage."
            fi
            
            # 2. Dans tous les cas, on déplace l'original vers old/
            echo "-> Archivage de l'original vers old/"
            mv "$img" "assets/data/eglise/img/noimh/old/"
          done