version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-search-api:latest
    container_name: github-search-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080" # <-- Modification ici pour lier uniquement à localhost
    environment:
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true