events { 
    worker_connections 1024; 
}

http {
    server_tokens off;

    # Serveur HTTP
    server {
        listen 80;
        server_name 217-182-206-51.sslip.io;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Serveur HTTPS
    server {
        listen 443 ssl;
        server_name 217-182-206-51.sslip.io;

        ssl_certificate /etc/letsencrypt/live/217-182-206-51.sslip.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/217-182-206-51.sslip.io/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # API Go
        location / {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Dashboard Prometheus
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}